Feat send email
LINCnil/pia-back pull request #134
Opened 2021-09-08 10:09 UTC by syl-p

2021-09-08 12:14 UTC, brunto requested changes
Il manque aussi le fichier de config, voir : https://github.com/atnos/profilplus/blob/develop/config/initializers/mailer.rb

2021-09-08 12:14 UTC, brunto commented on app/controllers/users_controller.rb
> +      UserMailer.with(user: user).uuid_created.deliver_now
Déplace le après le .save

2021-09-08 12:14 UTC, brunto commented on app/mailers/user_mailer.rb
> +      mail(to: @user.email, subject: "Votre compte Pia à été créé")
PIA en majuscule

2021-09-08 12:14 UTC, brunto commented on app/mailers/user_mailer.rb
> +      mail(to: @user.email, subject: "Votre compte Pia à été créé")
"à" sans accent

2021-09-08 12:14 UTC, brunto commented on config/locales/fr.yml
> +    uuid_created: "Votre compte à été créé, voilà votre uuid: "
à => a

2021-09-09 08:42 UTC, brunto requested changes

2021-09-09 08:42 UTC, brunto commented on config/locales/en.yml
> +    uuid_created: "Your pia account was created, your uuid is: "
PIA en majuscule

2021-09-09 08:42 UTC, brunto commented on app/mailers/application_mailer.rb
> +  default from: ENV["EMAIL_FROM"]
Utiliser les credentials plutôt

2021-09-09 08:42 UTC, brunto commented on config/locales/fr.yml
> +  hello: "Hello world"
Supprimer la ligne "Hello world"

2021-09-09 08:42 UTC, brunto commented on config/locales/en.yml
>    hello: "Hello world"
Supprimer la ligne "Hello world"

2021-09-09 09:10 UTC, syl-p commented on app/mailers/application_mailer.rb
> +  default from: ENV["EMAIL_FROM"]
même pour la configuration du smtp du coup ? ou juste pour l'email ?

2021-09-09 12:30 UTC, brunto approved these changes

2021-09-09 12:31 UTC, merged