feat: add relation user_pia
LINCnil/pia-back pull request #135
Opened 2021-09-10 08:34 UTC by syl-p

2021-09-10 13:12 UTC, brunto requested changes

2021-09-10 13:12 UTC, brunto commented on app/controllers/pias_controller.rb
> +  def testUserId(user_id)
Le nom des méthodes en ruby doit être avec des underscore.
testUserId => test_user_id
Idéalement il faudrait la nommer autrement qu'avec le préfix "test"

2021-09-10 13:12 UTC, brunto commented on app/controllers/pias_controller.rb
> +      return User.find(user_id.to_i)
```suggestion
     User.find(user_id.to_i)
```

2021-09-10 13:12 UTC, brunto commented on app/controllers/pias_controller.rb
> +      return user_id
```suggestion
     user_id
```

2021-09-10 13:12 UTC, brunto commented on app/controllers/pias_controller.rb
> +    end
Pas du tout DRY, il faudra refactorer cela.

2021-09-10 13:12 UTC, brunto commented on app/controllers/pias_controller.rb
> +      @pia.author_name = user.firstname + " " + user.lastname
utiliser plutôt : `"#{user.firstname} #{user.lastname}"`

2021-09-10 13:29 UTC, brunto approved these changes

2021-09-10 13:29 UTC, brunto commented on app/controllers/pias_controller.rb
> +        @pia.validator_name ="#{user.firstname} #{user.lastname}"
Il manque un espace après le "="

2021-09-10 13:29 UTC, brunto commented on app/controllers/pias_controller.rb
> +        @pia.evaluator_name = user.firstname + " " + user.lastname
"#{user.firstname} #{user.lastname}"

2021-09-10 13:29 UTC, brunto commented on app/controllers/pias_controller.rb
> +        @pia.author_name = user.firstname + " " + user.lastname
"#{user.firstname} #{user.lastname}"

2021-09-10 13:29 UTC, brunto commented on app/controllers/pias_controller.rb
> +      @pia.validator_name = user.firstname + " " + user.lastname
"#{user.firstname} #{user.lastname}"

2021-09-10 13:29 UTC, brunto commented on app/controllers/pias_controller.rb
> +      @pia.evaluator_name = user.firstname + " " + user.lastname
"#{user.firstname} #{user.lastname}"

2021-09-14 13:25 UTC, brunto requested changes

2021-09-14 13:25 UTC, brunto commented on app/controllers/pias_controller.rb
> +    return unless user.is_a?(User)
Always a new line after un return.
```suggestion
    return unless user.is_a?(User)

```

2021-09-14 13:25 UTC, brunto commented on app/controllers/pias_controller.rb
> +      return unless relation.present?
```suggestion
      return unless relation.present?

```

2021-09-14 13:25 UTC, brunto commented on app/serializers/pia_serializer.rb
> +        user =  User.find(up.user_id)
```suggestion
        user = User.find(up.user_id)
```

2021-09-21 12:26 UTC, kevin-atnos approved these changes

2021-09-21 14:02 UTC, brunto approved these changes

2021-09-21 14:02 UTC, merged