Feat prepare reset account password
LINCnil/pia-back pull request #137
Opened 2021-09-24 15:43 UTC by syl-p

2021-11-02 10:28 UTC, syl-p commented on app/controllers/users_controller.rb
> +    password = "-@A"+SecureRandom.base64(12)
this way ?

```  
    password_form = (0..9).to_a + ('A'..'z').to_a + ('!'..'?').to_a
    password = password_form.shuffle[0..12].join
    
    user.password = password
    user.password_confirmation = password
    
```

2021-11-02 13:02 UTC, brunto requested changes

2021-11-02 13:02 UTC, brunto commented on app/controllers/users_controller.rb
> +    .except("access_type")
Il faudrait aligner avec le .permit ou tout mettre sur la même ligne

2021-11-02 13:02 UTC, brunto commented on app/models/user.rb
> +
Ligne en trop

2021-11-02 13:02 UTC, brunto commented on app/models/user.rb
> +  validates :password_confirmation, presence: true, on: :update, unless: lambda {|user| user.password.blank? }
```suggestion
  validates :password_confirmation, presence: true, on: :update, unless: lambda { |user| user.password.blank? }
```

2021-11-02 13:02 UTC, brunto commented on app/controllers/users_controller.rb
> +          render json: {}, status:  406 # Not acceptable
```suggestion
          render json: {}, status: 406 # Not acceptable
```

2021-11-02 13:02 UTC, brunto commented on app/controllers/users_controller.rb
> +      render json: {}, status:  404
```suggestion
      render json: {}, status: 404
```

2021-11-03 09:07 UTC, brunto approved these changes

2021-11-03 09:07 UTC, merged